// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package emailservice

import (
	"context"
	"errors"
	"github.com/ServiceWeaver/onlineboutique/types"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/ServiceWeaver/onlineboutique/emailservice/EmailService",
		Iface: reflect.TypeOf((*EmailService)(nil)).Elem(),
		Impl:  reflect.TypeOf(impl{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return emailService_local_stub{impl: impl.(EmailService), tracer: tracer, sendOrderConfirmationMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/ServiceWeaver/onlineboutique/emailservice/EmailService", Method: "SendOrderConfirmation", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return emailService_client_stub{stub: stub, sendOrderConfirmationMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/ServiceWeaver/onlineboutique/emailservice/EmailService", Method: "SendOrderConfirmation", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return emailService_server_stub{impl: impl.(EmailService), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return emailService_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[EmailService] = (*impl)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*impl)(nil)

// Local stub implementations.

type emailService_local_stub struct {
	impl                         EmailService
	tracer                       trace.Tracer
	sendOrderConfirmationMetrics *codegen.MethodMetrics
}

// Check that emailService_local_stub implements the EmailService interface.
var _ EmailService = (*emailService_local_stub)(nil)

func (s emailService_local_stub) SendOrderConfirmation(ctx context.Context, a0 string, a1 types.Order) (err error) {
	// Update metrics.
	begin := s.sendOrderConfirmationMetrics.Begin()
	defer func() { s.sendOrderConfirmationMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "emailservice.EmailService.SendOrderConfirmation", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.SendOrderConfirmation(ctx, a0, a1)
}

// Client stub implementations.

type emailService_client_stub struct {
	stub                         codegen.Stub
	sendOrderConfirmationMetrics *codegen.MethodMetrics
}

// Check that emailService_client_stub implements the EmailService interface.
var _ EmailService = (*emailService_client_stub)(nil)

func (s emailService_client_stub) SendOrderConfirmation(ctx context.Context, a0 string, a1 types.Order) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.sendOrderConfirmationMetrics.Begin()
	defer func() { s.sendOrderConfirmationMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "emailservice.EmailService.SendOrderConfirmation", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	enc.String(a0)
	(a1).WeaverMarshal(enc)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][20]struct{}](`

ERROR: You generated this file with 'weaver generate' (devel) (codegen
version v0.20.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type emailService_server_stub struct {
	impl    EmailService
	addLoad func(key uint64, load float64)
}

// Check that emailService_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*emailService_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s emailService_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "SendOrderConfirmation":
		return s.sendOrderConfirmation
	default:
		return nil
	}
}

func (s emailService_server_stub) sendOrderConfirmation(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 types.Order
	(&a1).WeaverUnmarshal(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.SendOrderConfirmation(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type emailService_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that emailService_reflect_stub implements the EmailService interface.
var _ EmailService = (*emailService_reflect_stub)(nil)

func (s emailService_reflect_stub) SendOrderConfirmation(ctx context.Context, a0 string, a1 types.Order) (err error) {
	err = s.caller("SendOrderConfirmation", ctx, []any{a0, a1}, []any{})
	return
}
