// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package recommendationservice

import (
	"context"
	"errors"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/ServiceWeaver/onlineboutique/recommendationservice/RecommendationService",
		Iface: reflect.TypeOf((*RecommendationService)(nil)).Elem(),
		Impl:  reflect.TypeOf(impl{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return recommendationService_local_stub{impl: impl.(RecommendationService), tracer: tracer, listRecommendationsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/ServiceWeaver/onlineboutique/recommendationservice/RecommendationService", Method: "ListRecommendations", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return recommendationService_client_stub{stub: stub, listRecommendationsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/ServiceWeaver/onlineboutique/recommendationservice/RecommendationService", Method: "ListRecommendations", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return recommendationService_server_stub{impl: impl.(RecommendationService), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return recommendationService_reflect_stub{caller: caller}
		},
		RefData: "⟦f266fa1e:wEaVeReDgE:github.com/ServiceWeaver/onlineboutique/recommendationservice/RecommendationService→github.com/ServiceWeaver/onlineboutique/productcatalogservice/ProductCatalogService⟧\n",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[RecommendationService] = (*impl)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*impl)(nil)

// Local stub implementations.

type recommendationService_local_stub struct {
	impl                       RecommendationService
	tracer                     trace.Tracer
	listRecommendationsMetrics *codegen.MethodMetrics
}

// Check that recommendationService_local_stub implements the RecommendationService interface.
var _ RecommendationService = (*recommendationService_local_stub)(nil)

func (s recommendationService_local_stub) ListRecommendations(ctx context.Context, a0 string, a1 []string) (r0 []string, err error) {
	// Update metrics.
	begin := s.listRecommendationsMetrics.Begin()
	defer func() { s.listRecommendationsMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "recommendationservice.RecommendationService.ListRecommendations", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.ListRecommendations(ctx, a0, a1)
}

// Client stub implementations.

type recommendationService_client_stub struct {
	stub                       codegen.Stub
	listRecommendationsMetrics *codegen.MethodMetrics
}

// Check that recommendationService_client_stub implements the RecommendationService interface.
var _ RecommendationService = (*recommendationService_client_stub)(nil)

func (s recommendationService_client_stub) ListRecommendations(ctx context.Context, a0 string, a1 []string) (r0 []string, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.listRecommendationsMetrics.Begin()
	defer func() { s.listRecommendationsMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "recommendationservice.RecommendationService.ListRecommendations", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	enc.String(a0)
	serviceweaver_enc_slice_string_4af10117(enc, a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_slice_string_4af10117(dec)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.23.2 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type recommendationService_server_stub struct {
	impl    RecommendationService
	addLoad func(key uint64, load float64)
}

// Check that recommendationService_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*recommendationService_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s recommendationService_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "ListRecommendations":
		return s.listRecommendations
	default:
		return nil
	}
}

func (s recommendationService_server_stub) listRecommendations(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 []string
	a1 = serviceweaver_dec_slice_string_4af10117(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.ListRecommendations(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_string_4af10117(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type recommendationService_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that recommendationService_reflect_stub implements the RecommendationService interface.
var _ RecommendationService = (*recommendationService_reflect_stub)(nil)

func (s recommendationService_reflect_stub) ListRecommendations(ctx context.Context, a0 string, a1 []string) (r0 []string, err error) {
	err = s.caller("ListRecommendations", ctx, []any{a0, a1}, []any{&r0})
	return
}

// Encoding/decoding implementations.

func serviceweaver_enc_slice_string_4af10117(enc *codegen.Encoder, arg []string) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		enc.String(arg[i])
	}
}

func serviceweaver_dec_slice_string_4af10117(dec *codegen.Decoder) []string {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]string, n)
	for i := 0; i < n; i++ {
		res[i] = dec.String()
	}
	return res
}
